[package]

id = "chorus-git-extension"
publisher = "chorus"
version = "0.0.0"
description = "Git extension for chorus"

[extension]

provides = ["view.components", "keybindings", "commands"]

[[view.components]]

name = "sidebar-view"
path = "./dist/sidebar.js"

[[view.components]]

name = "full-view"
path = "./dist/full.js"

[[commands]]
id = "chorus.open-scm-sidebar"
name = "Chorus: Open SCM Sidebar"
description = "Opens the SCM view"
